export const ListUrl =[
    {
        link1:"https://github.com/walid-tab/Search-Job-App"
    },
    {
        link2:"https://github.com/walid-tab/Movie-App-React"
    },
    {
        link3:"https://github.com/walid-tab/CRUD-User-React-app-with-Firebase-"
    },
    {
        link4:"https://github.com/walid-tab/todoList_react_app_using_Typescript"
    },
    {
        link5:"https://github.com/walid-tab/Quiz-App-React"
    },
    {
        link6:"https://github.com/walid-tab/MERN-App-CRUD"
    }
]